name: lspk
services:
  db:
    image: postgres:latest
    container_name: lspk-postgres
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: lspkdb
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - lspk-postgres-volume:/var/lib/postgresql/data
volumes:
  lspk-postgres-volume:
